PROCESS_ERROR = "Command raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message",
"Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body\nIn message_reference: Unknown message",
"Command raised an exception: AttributeError: 'ClientUser' object has no attribute 'create_dm'",
"Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In message_reference: Unknown message",
"Command raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message",
"Command raised an exception: HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.",
"Command raised an exception: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'",
"Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In message_reference: Unknown message",
"returnCommand raised an exception: AttributeError: 'MiningCog' object has no attribute 'get_prefix'",
"Command raised an exception: SyntaxError: invalid syntax (<string>, line 1)",
"Command raised an exception: TypeError: argument of type 'NoneType' is not iterable",
"Command raised an exception: NotFound: 404 Not Found (error code: 0): Interaction is unknown (you have already responded to the interaction or responding took too long)",
"Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In message_reference: Unknown message",
"Command raised an exception: Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user",
"Command raised an exception: UnboundLocalError: local variable 'member' referenced before assignment",
"Command raised an exception: TypeError: 'NoneType' object is not subscriptable"